name: testcase_dashboard
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  csv: ^6.0.0
  dartx: ^1.2.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  intersperse: ^2.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  popover: ^0.3.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  web: ^1.1.1
  yaru: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  web_benchmarks: ^4.0.0
  flutter_lints: ^5.0.0
  dependency_validator: ^5.0.2
  build_runner: ^2.4.15
  freezed: ^3.0.6
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
