version = 1

[[annotations]]
path = "test_observer.code-workspace"
SPDX-FileCopyrightText = "2026 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "backend/.vscode/settings.json",
    "backend/charm/.vscode/settings.json",
    "frontend/charm/.vscode/settings.json"
]
SPDX-FileCopyrightText = "2026 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "backend/charm/lib/charms/data_platform_libs/v0/data_interfaces.py"
SPDX-FileCopyrightText = "2023 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "backend/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py",
    "backend/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py",
    "backend/charm/lib/charms/redis_k8s/v0/redis.py"
]
SPDX-FileCopyrightText = "2021 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "backend/charm/lib/charms/nginx_ingress_integrator/v0/nginx_route.py",
    "frontend/charm/lib/charms/nginx_ingress_integrator/v0/nginx_route.py"
]
SPDX-FileCopyrightText = "2024 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "backend/charm/src/grafana_dashboards/product_artifact_deepdive.json"
SPDX-FileCopyrightText = "2026 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "backend/schemata/openapi.json"
SPDX-FileCopyrightText = "2026 Canonical Ltd."
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [
    "backend/tests/test_data/Packages-proposed.gz",
    "backend/tests/test_data/Packages-updates.gz"
]
SPDX-FileCopyrightText = "2023 Canonical Ltd."
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "backend/uv.lock"
SPDX-FileCopyrightText = "2025 Canonical Ltd."
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "docs/**/*"
SPDX-FileCopyrightText = "2025 Canonical Ltd."
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "frontend/.metadata",
    "frontend/.vscode/launch.json",
    "frontend/assets/*",
    "frontend/frontend.iml",
    "frontend/pubspec.lock",
    "frontend/pubspec.yaml",
    "frontend/web/icons/*",
    "frontend/web/index.html",
    "frontend/web/manifest.json"
]
SPDX-FileCopyrightText = "2023 Canonical Ltd."
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "renovate.json"
SPDX-FileCopyrightText = "2024 Canonical Ltd."
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "terraform/cloud-init.yaml"
SPDX-FileCopyrightText = "2023 Canonical Ltd."
SPDX-License-Identifier = "Apache-2.0"
