options:
  port:
    default: 30000
    description: The port to listen on for incoming HTTP requests.
    type: int

  hostname:
    default: test-observer-api
    description: Public hostname for the service.
    type: string
  sentry_dsn:
    description: value for SENTRY_DSN that is used to send errors to sentry
    type: string
