name: Run charm tests
on:
  pull_request:
    branches:
      - main
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  lint-report:
    name: Lint and format report
    runs-on: [self-hosted, linux, large]
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e lint
    defaults:
      run:
        working-directory: ./frontend/charm

  static-analysis:
    name: Static analysis
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static
    defaults:
      run:
        working-directory: ./frontend/charm

  unit-tests-with-coverage:
    name: Unit tests
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e unit
    defaults:
      run:
        working-directory: ./frontend/charm
