on:
  pull_request:
    branches:
      - main
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  build:
    name: Release test-observer-api charm to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- name: Select charmhub channel
      #  uses: canonical/charming-actions/channel@2.2.0
      #  id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.2.0
        with:
          charm-path: "backend/charm"
          credentials: "${{ secrets.CHARMHUB_AUTH_API }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "true"
          channel: edge # "${{ steps.channel.outputs.name }}"
