#cloud-config

# This enables password authentication,
# which removes the need for an SSH key
ssh_pwauth: true

users:
  - default
  - name: SPREAD_REPLACE_USERNAME
    # This enables this specific user to login with just a password and no SSH key
    lock_passwd: false
    # With lock_passwd set to false, we need to set a password
    plain_text_passwd: SPREAD_REPLACE_PASSWORD
    sudo: ALL=(ALL) NOPASSWD:ALL
